# This Docker Compose file can be used to quickly bootup Dgraph Zero
# and Alpha in different Docker containers.

# It mounts data/dgraph on the host machine to /dgraph within the
# container. Run `docker-compose up` to start Dgraph.

version: "3.9"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - ./data/dgraph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    #restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - ./data/dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    #restart: on-failure
    command: dgraph alpha --security whitelist=172.16.0.0/12 --my=alpha:7080 --zero=zero:5080